### ISSUE TITLE
support generics

### ISSUE THREAD

**Issue by cq-z** [i-love-flamingo/dingo#29]
support 1.17 generics
like 
```
instance, err := injector.GetInstance(new(BillingService))
	if err != nil {
		panic(err)
	}
    billingService := instance.(BillingService) 
```
do not
`billingService := instance.(BillingService) `

**Comment by bastianccm** [comment]
Hey @cq-z 

it's on the roadmap, but we'll need to wait for Go 1.18 to fully support generics:
https://github.com/golang/go/issues/47737
(we can't export GetInstance[T] yet)

**Comment by cq-z** [comment]
is good！

**Comment by xqzhou** [comment]
Is generic now supported or not?
